Wa 2 routes city suite
nathanmariedev/meteo pull request #3
Opened 2023-04-17 10:59 UTC by nathanmariedev

2023-04-17 13:39 UTC, NathanGenaudeau1 commented
Oublie pas de repasser sur les tous fichiers que t'as modifié pour éviter les erreurs ESLint. (Pour les fichiers de migrations/seeds fais pas gaffe à l'erreur du type `Expected knex to have a type annotation`)

2023-04-17 15:39 UTC, NathanGenaudeau1 requested changes

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/user/classes/user.class.ts
>    @ApiProperty()
Il faut remplir cette propriété à chaque fois (pas que dans ce fichier), elle sert pour le swagger. (ex [ici](https://github.com/wecraftapps/bingobot/blob/master/src/user/classes/user.class.ts) si tu veux). Il faut aussi essayer de préciser un maximum les attributs. Par exemple dans la classe `City`, pour les champs string, mettre un `@IsString()`

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/user/user.controller.ts
> +    console.log('user');
N'oublie pas de clean ton code avant de le push

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/user/classes/user.class.ts
> +  IsEmail,
Oublie pas d'enlever les imports inutilisés

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/user/user.controller.ts
>    @Get('/:id')
Il faut rajouter des propriétés pour le swagger afin de donner un maximum d'informations (doc [ici](https://docs.nestjs.com/openapi/operations#responses)) Par exemple pour ce `Get`, la propriété  `@ApiOkResponse()` permet de dire ce que la route renvoie en cas de succès

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/user/user.controller.ts
> +    const user = await this.userService.findOneById(id);
Tu peux ajouter une exception si le `User` n'existe pas pour que la route renvoie quelque chose. Actuellement elle ne renvoie rien si on met un `id` qui n'existe pas

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/user/user.controller.ts
> +    return user;
Comme tu ne fais rien entre ces 2 lignes tu peux directement retourner sans instancier une variable :
`return await this.userService.add(userToAdd);`

2023-04-17 15:39 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +    const addCity = await this.pg.raw(
Tu n'utilises pas la variable et la fonction ne retourne rien donc pas besoin de la déclarer

2023-04-18 08:47 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +const API_KEY = '1e3804f9ba78545c499d5dd4af53caf47fce3f32dd8d4096e003542c12f37144';
Il ne faut pas mettre des variables sensibles dans le code. Tu dois les mettre dans ton `config.env` (et le `config.env.dist` mais à vide). Ensuite pour les utiliser dans ton code, tu dois passer par `process.env` (doc [ici](https://docs.nestjs.com/techniques/configuration) si tu veux te renseigner). Par exemple pour l'url de l'api, tu écris : `process.env.API_URL`

2023-04-18 08:47 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +    return req.rows;
Pense à rajouter le type de retour pour préciser. Ici c'est `return req.rows as City[];`

2023-04-18 08:47 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +      return req.rows[0];
Pareil ici

2023-04-18 08:47 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +    let result: Array<City>;
Pourquoi tu déclares ta variable ici ? Tu peux juste le faire plus bas au moment où tu l'utilises

2023-04-18 08:47 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +    // eslint-disable-next-line prefer-const
Pas besoin de ça comme tu vas changer la variable en const

2023-04-18 08:47 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +    result = data.map(
Tu peux déclarer la variable sur la même ligne avec `const result = ...`

2023-04-18 09:41 UTC, nathanmariedev commented on backend/src/city/models/city.model.ts
> +    const addCity = await this.pg.raw(
Quelle variable?

2023-04-18 12:37 UTC, NathanGenaudeau1 commented on backend/src/city/models/city.model.ts
> +    const addCity = await this.pg.raw(
le `const addCity = await ...` tu peux mettre juste `await ...` comme tu réutilises pas la variable

2023-04-18 13:19 UTC, closed without merging